#!/usr/bin/env python3
"""Write curriculum/video/REVIEW.md: one page to walk through every segment video.

    python3 curriculum/video/review.py

For each segment: title, voice, length, word count, the slide list, the pause question, and the
items from SNN/CHECK.md that the program should confirm before showing it. Regenerate after any
render; it reads videos/SNN.mp4 for the running time.
"""
import json, os, re, subprocess, sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))


def duration(mp4):
    try:
        import imageio_ffmpeg
        ff = imageio_ffmpeg.get_ffmpeg_exe()
        out = subprocess.run([ff, "-i", mp4], capture_output=True, text=True).stderr
        m = re.search(r"Duration: (\d+):(\d+):(\d+)\.(\d+)", out)
        return f"{int(m.group(2))}:{int(m.group(3)):02d}" if m else "?"
    except Exception:
        return "?"


def main():
    segs = sorted(d for d in os.listdir(HERE) if re.fullmatch(r"S\d+", d) and os.path.exists(os.path.join(HERE, d, "cues.json")))
    out = ["# Segment videos: review sheet", "",
           "Generated by `review.py`. One block per segment: what it says, what it shows, and what the program",
           "should confirm before it is shown (from each segment's CHECK.md). Watch the MP4, then edit",
           "`SNN/cues.json` and re-render; only the cues whose words changed are re-narrated.", "",
           "| # | Title | Voice | Length | Words | Video |", "|---|---|---|---|---|---|"]
    blocks = []
    for seg in segs:
        n = int(seg[1:]); spec = json.load(open(os.path.join(HERE, seg, "cues.json"), encoding="utf-8"))
        meta, cues = spec["meta"], spec["cues"]
        voice = (meta.get("voice") or ("josh" if n % 2 else "nichalia")).title()
        mp4 = os.path.join(ROOT, "videos", f"{seg}.mp4")
        dur = duration(mp4) if os.path.exists(mp4) else "not rendered"
        words = sum(len(c.get("say", "").split()) for c in cues)
        out.append(f"| {seg} | {meta['title']} | {voice} | {dur} | {words} | `videos/{seg}.mp4` |")
        b = [f"## {seg}: {meta['title']}", "", f"{meta.get('description', '')}", "",
             f"Voice {voice}, {dur}, {words} words, {len(cues)} cues. Cue file `curriculum/video/{seg}/cues.json`.", "", "Slides:", ""]
        for i, c in enumerate(cues, 1):
            if c["type"] == "pause":
                b.append(f"{i}. **pause**: _{c['question']}_")
            else:
                head = c.get("heading") or c.get("title") or c.get("text", "")
                b.append(f"{i}. {c['type']}: {head}")
        chk = os.path.join(HERE, seg, "CHECK.md")
        if os.path.exists(chk):
            b += ["", "Confirm before showing:", ""]
            for ln in open(chk, encoding="utf-8"):
                ln = ln.rstrip()
                if ln.startswith(("-", "*")):
                    b.append("- " + ln.lstrip("-* ").strip())
        blocks.append("\n".join(b))
    out += [""] + ["\n\n".join(blocks)]
    open(os.path.join(HERE, "REVIEW.md"), "w", encoding="utf-8").write("\n".join(out) + "\n")
    print("wrote curriculum/video/REVIEW.md for", ", ".join(segs))


if __name__ == "__main__":
    main()
